version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '03:00'
      timezone: 'Europe/Helsinki'
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "/benchmark"
    schedule:
      interval: daily
      time: '03:00'
      timezone: 'Europe/Helsinki'
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '03:00'
      timezone: 'Europe/Helsinki'
    open-pull-requests-limit: 99
